import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const STORAGE_KEY = 'eads_lang';

const translations = {
  en: {
    common: {
      loading: 'Loading…',
    },
    student: {
      programsTitle: 'Available scholarship programs',
      loadingPrograms: 'Loading programs…',
      loadError: 'Failed to load programs',
      noOpen: 'No open programs right now.',
      noOpenHint:
        'If you just set up the database, run the seed script so providers and sample scholarship programs are created.',
      apply: 'Apply',
      continueApplication: 'Continue application',
      applied: 'Applied',
      perBeneficiary: 'BDT {n} per beneficiary',
      deadline: 'Deadline',
      draftNote: 'Draft — finish and submit to the provider.',
      myAppsTitle: 'My applications',
      noAppsLine: 'No applications yet.',
      browseToApply: 'Browse programs',
      toApply: 'to apply.',
      amount: 'Amount',
      started: 'Started',
      submittedOn: 'Submitted',
      continueLink: 'Continue application',
      editLink: 'Edit application',
      eligibility: 'Eligibility',
      duplicateWarning: 'Duplicate aid warning was raised.',
      draftBadge: 'draft',
    },
    profile: {
      title: 'My profile',
      lead: 'Keep your information up to date — it directly affects your eligibility score and aid applications.',
      loadError: 'Could not load profile',
      updateError: 'Update failed',
      saved: 'Profile saved successfully',
      savedUp: 'Profile saved! Eligibility score ↑ {diff} pts ({score}/100)',
      savedDown: 'Profile saved. Eligibility score ↓ {diff} pts ({score}/100)',
      loading: 'Loading profile…',
      scoreTitle: 'Eligibility score',
      scoreBlurb: 'Your score is calculated based on various factors.',
      lastUpdated: 'Last updated',
      documents: 'Documents',
      ptsBonus: '(+{n} pts)',
      verified: 'Verified',
      rejected: 'Rejected',
      unverified: 'Unverified',
      personalInfo: 'Personal information',
      fullName: 'Full name',
      phone: 'Phone',
      gender: 'Gender',
      select: '— Select —',
      male: 'Male',
      female: 'Female',
      location: 'Location',
      district: 'District',
      upazila: 'Upazila',
      institution: 'Institution',
      institutionName: 'Institution name',
      institutionType: 'Institution type',
      school: 'School',
      college: 'College',
      university: 'University',
      financial: 'Financial information',
      monthlyIncome: 'Monthly household income (BDT)',
      familySize: 'Family size',
      academic: 'Academic performance',
      attendance: 'Attendance %',
      cgpa: 'CGPA (0–4)',
      saving: 'Saving & recalculating score…',
      save: 'Save changes',
      scoreHigh: 'High eligibility',
      scoreModerate: 'Moderate eligibility',
      scoreLow: 'Low eligibility',
      scoreNeedsData: 'Needs more data',
    },
    nav: {
      home: 'Home',
      howItWorks: 'How it works',
      forStudents: 'For Students',
      forProviders: 'For Providers',
      dashboard: 'Dashboard',
      programs: 'Programs',
      applications: 'Applications',
      reviewApplications: 'Review applications',
      profile: 'Profile',
      students: 'Students',
      providers: 'Providers',
      login: 'Log in',
      register: 'Register',
      logout: 'Logout',
    },
    home: {
      title: 'Education Aid Disbursement System',
      titleAccent: 'Education Aid',
      titleRest: ' Disbursement System',
      subtitle: 'Connecting talented students in Bangladesh with verified scholarship providers. Fair, transparent, and built for impact.',
      applyStudent: 'Apply as Student',
      registerProvider: 'Register as Provider',
      howItWorks: 'How it works',
      students: 'Students',
      studentsDesc: 'Create your profile with academic and financial details. Get matched to eligible scholarships and track applications in one place.',
      providers: 'Providers',
      providersDesc: 'NGOs, banks, and donors can publish programs, set criteria, and disburse funds with full transparency and duplicate-aid checks.',
      transparency: 'Transparency',
      transparencyDesc: 'Eligibility checks, ranking by need and merit, and regional analytics ensure aid reaches the right students across districts and upazilas.',
      getStarted: 'Get started',
      joinProvider: 'Join as provider',
      studentsSupported: 'Students supported',
      verifiedProviders: 'Verified providers',
      nationwide: 'Nationwide',
      districtCoverage: 'District & upazila coverage',
      readyTitle: 'Ready to get started?',
      readyText: 'Log in to your account or create one today.',
      registerStudent: 'Register as student',
      registerProviderLink: 'Register as provider',
      dynamicFunding: 'Dynamic Funding',
      dynamicFundingDesc: 'Budgeted programs allocate support fairly across eligible learners.',
      impactTracking: 'Impact Tracking',
      impactTrackingDesc:
        'Every disbursement is tracked with status updates and clear reporting.',
      newHeroBadge: 'Radically transparent funding',
      heroTitleHighlight: 'Alokdaar:',
      heroTitleRest: 'Ensuring education for all',
      heroSubtitle:
        'We bridge the gap between human potential and educational access through a verifiable, blockchain-backed aid ecosystem. Honest aid for honest growth.',
      startApplication: 'Start your application',
      howWeVerify: 'How we verify',
      demoGrantTitle: 'New grant issued',
      demoGrantSubtitle: '৳2,400 to Rafiq Miah',
      heroImageAlt: 'Bangladeshi student smiling while studying',
      heroVerified: 'Verified',
      statStudentsAssisted: 'Students assisted',
      statFundsDisbursed: 'Funds disbursed',
      statTransparencyRate: 'Transparency rate',
      conduitTitle: 'The conduit of progress',
      conduitSubtitle: 'A transparent, structured path from application to meaningful support.',
      radicalTitle: 'Radical transparency as a standard',
      radicalLead:
        'Real-time visibility into how aid moves from donor funds to student outcomes.',
      trustPoint1: 'Third-party quality checks',
      trustPoint2: 'Clear audit trails for every disbursement',
      trustPoint3: 'Zero hidden-fee distribution',
      directFunding: 'Direct funding',
      directFundingDesc: 'Support reaches students and institutions through verified channels.',
      studentJourney: 'Student journey',
      studentJourneyDesc: 'Track progress from first application to scholarship completion.',
      verificationAi: 'Verification AI',
      verificationAiDesc: 'Identity and eligibility checks reduce fraud and improve trust.',
      globalSecurity: 'Global security',
      globalSecurityDesc: 'Modern safeguards protect student and provider information.',
      ctaTitle: 'Ready to change a life?',
      ctaText: 'Whether you are a student or a donor, your journey starts here.',
      getStartedToday: 'Get started today',
    },
    footer: {
      tagline: 'Education Aid Disbursement System — fair and transparent educational aid for students in Bangladesh.',
      students: 'Students',
      providers: 'Providers',
      system: 'System',
      browsePrograms: 'Browse programs',
      copyright: 'Education Aid Disbursement System. Built for Bangladeshi students and scholarship providers.',
    },
    help: {
      title: 'Help center',
      intro: 'Quick answers about EADS and how to get personal support.',
      faqSection: 'Common questions',
      q1: 'How do I apply for a scholarship program?',
      a1:
        'Log in as a student, go to “Apply for aid”, choose an open program, and submit the required details and documents.',
      q2: 'My application is still pending. What should I do?',
      a2:
        'Pending means the provider is reviewing your application. Keep your profile and documents up to date; you will be notified when the status changes.',
      q3: 'How do providers publish new programs?',
      a3:
        'In the provider portal, use “New program” to set the budget, eligibility rules, and application window for verified students.',
      q4: 'Who do I contact for account or technical problems?',
      a4: 'Use the support email below. For program-specific questions, you can also reach out to the provider running that scholarship.',
      contactTitle: 'Contact support',
      contactLead: 'We usually respond within two business days.',
      emailLabel: 'Support email',
      copy: 'Copy',
      copyDone: 'Copied',
      copied: 'Copied to clipboard',
      openMail: 'Open in email',
    },
    rejections: {
      nav: 'Rejections',
      providerTitle: 'Rejected applications',
      adminTitle: 'Rejections',
      leadProvider: 'Students your organization declined for a program. You can return to a program to review other applicants at any time.',
      leadAdmin: 'Application denials from providers and profile verification rejections by administrators.',
      emptyApps: 'No rejected applications on record for your programs.',
      emptyAppsAdmin: 'No rejected applications in the system yet.',
      emptyProfile: 'No students with rejected profile verification.',
      applicationSection: 'Application rejections',
      profileSection: 'Profile verification rejections',
      student: 'Student',
      program: 'Program',
      provider: 'Provider',
      email: 'Email',
      reason: 'Reason',
      reviewed: 'Reviewed',
      notProvided: '—',
      openProgram: 'Program applications',
      openStudent: 'View student',
    },
    dash: {
      studentPortal: 'Student portal',
      providerPortal: 'Institutional portal',
      adminPortal: 'Administration',
      systemTagline: 'Education Aid System',
      applyForAid: 'Apply for aid',
      disbursementStatus: 'Disbursement status',
      notifications: 'Notifications',
      newProgram: 'New program',
      reviewApplicationsLead:
        'Choose a program below to open its queue. Approve or reject applications that students have submitted to your organization.',
      systemAnalytics: 'System analytics',
      settings: 'Settings',
      needSupport: 'Need support?',
      helpCenter: 'Help center',
      welcomeBack: 'Welcome back',
      systemOverview: 'Overview of education aid distribution and verification.',
      profileCard: 'Profile',
      applicationStatus: 'Application status',
      eligibilityScore: 'Need & merit index',
      recentApplications: 'Recent applications',
      activeScholarships: 'Applications overview',
      academicInsight: 'Your profile insight',
      insightBody:
        'Based on your attendance, CGPA, and financial need score, keep your documents verified to stay eligible for new programs.',
      explorePrograms: 'Explore programs',
      totalPrograms: 'Programs',
      totalDisbursedLabel: 'Total disbursed (all programs)',
      activeScholars: 'Active beneficiaries',
      programProgress: 'Program funding',
      impactNote: 'Transparent tracking helps ensure aid reaches verified students on time.',
      verificationCard: 'Verification',
      verificationBody:
        'Keep income proof and transcripts up to date so providers can review your application faster.',
      distributionByRegion: 'Regional activity (illustrative)',
      approvalRatio: 'Application pipeline',
      approved: 'Approved',
      rejected: 'Rejected',
      pending: 'Pending',
      duplicateAlerts: 'Duplicate aid checks',
      duplicateBody: 'The system flags overlapping approvals so administrators can review conflicts.',
      quickActions: 'Quick actions',
      verifyStudents: 'Review students',
      approveProviders: 'Review providers',
      disbursements: 'Disbursements',
      impactReport: 'Reports',
      recentDisbursements: 'Recent activity',
      pendingProviders: 'Provider oversight',
      securityCard: 'Audit & security',
      securityBody: 'Important actions are logged for transparency and accountability.',
      generateExport: 'Generate export',
      reportPeriod: 'Latest summary',
      attendanceShort: 'Attendance',
      totalAid: 'Total aid received',
      needLabel: 'Need score',
      stepProfile: 'Profile & documents',
      stepApply: 'Applications',
      stepDecision: 'Decisions',
      submitted: 'submitted',
      noApplicationsYet: 'No applications yet.',
      pendingLower: 'pending review',
      approvedLower: 'approved',
      eligibilityBlurb: 'Higher scores reflect greater financial need relative to merit indicators.',
      compositeIndex: 'Composite index (0–100)',
      noNotifications: 'No new notifications.',
      markAllRead: 'Mark all as read',
      cancel: 'Cancel',
      rejectAppTitle: 'Reject application',
      rejectAppLead: 'The applicant will be notified. You may add an optional note explaining the decision.',
      rejectAppStudent: 'Applicant',
      rejectAppReason: 'Reason (optional)',
      confirmReject: 'Confirm rejection',
      working: 'Working…',
      withdrawFunds: 'Withdraw balance',
      withdrawNoBalance: 'No available balance to withdraw yet.',
      withdrawTitle: 'Withdraw to your account',
      withdrawAvailable: 'Available balance:',
      withdrawMethod: 'Payout method',
      withdrawAmount: 'Amount (BDT)',
      withdrawWalletNumber: 'Mobile wallet number',
      withdrawBankName: 'Bank name',
      withdrawAccountName: 'Account holder name',
      withdrawAccountNumber: 'Account number',
      withdrawBranch: 'Branch (optional)',
      withdrawRouting: 'Routing number (optional)',
      withdrawNote:
        'Funds will be sent to the details you provide. Ensure your number or bank account is correct.',
      withdrawInvalidAmount: 'Enter a valid whole taka amount (at least ৳1).',
      withdrawExceedsBalance: 'That amount is more than your available balance.',
      submitWithdrawal: 'Submit withdrawal',
      withdrawSuccess: 'Withdrawal request submitted.',
      withdrawError: 'Could not submit withdrawal.',
      withdrawHistory: 'Withdrawal requests',
      noWithdrawals: 'No withdrawal requests yet.',
      disburseModalTitle: 'Record disbursement',
      disburseModalLead:
        'Confirm funds for this approved application. This updates the program budget and credits the student.',
      disburseAmount: 'Amount (BDT)',
      disburseMethod: 'Payment method',
      disburseRef: 'Transaction reference',
      disburseReleaseDate: 'Release date',
      disburseConfirm: 'Confirm & record',
      disburseStudent: 'Student',
      disburseProgram: 'Program',
      disburseDefault: 'Default amount',
      disburseFundLeft: 'Program fund remaining',
      noDisbursements: 'No disbursements recorded yet.',
      providerLead:
        'Configure scholarship programs and monitor how funds move to verified students.',
      createProgramTitle: 'Programs & funding',
      createProgramSub: 'Launch a new aid cycle with clear budget and beneficiary limits.',
      createProgramHint:
        'Use “New program” to set amount per student, maximum beneficiaries, and eligibility.',
      activePrograms: 'active',
      viewAll: 'View all',
      noProgramsYet: 'No programs yet. Create one to start receiving applications.',
      beneficiaryLine: 'Beneficiaries',
      disbursedShort: 'disbursed',
      totalShort: 'total',
      transparencyTitle: 'Fair, traceable disbursements',
      atRiskBadge: 'At-risk',
      loading: 'Loading dashboard…',
      exportSoon: 'Export will include current filters (coming soon).',
      pendingQueue: 'Pending review',
      duplicateHint: 'Review overlapping approvals from the Applications and Disbursements modules.',
      totalStudents: 'students',
      totalProviders: 'providers',
      auditLog: 'Audit trail',
      colAction: 'Action',
      colResource: 'Resource',
      colUser: 'User',
      colTime: 'Time',
      activeProgramsLabel: 'Active programs',
      fraudReview: 'Fraud review',
      disburseAid: 'Disburse aid',
      cgpaLabel: 'CGPA',
      accountBalance: 'Account balance',
      unverified: 'Unverified',
      downloadReport: 'Download report (PDF)',
      downloading: 'Downloading…',
      idLabel: 'ID',
      reportDownloaded: 'Report downloaded',
      reportFailed: 'Report generation failed',
      reportFailedGen: 'Failed to generate report',
      downloadReportError: 'Error downloading report',
      themeLight: 'Light mode',
      themeDark: 'Dark mode',
      navOpen: 'Open navigation',
      navClose: 'Close navigation',
      navExpand: 'Expand sidebar',
      navCollapse: 'Collapse sidebar',
      appStatus: {
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
      },
      disbStatus: {
        completed: 'Completed',
        pending: 'Pending',
        failed: 'Failed',
        processing: 'Processing',
      },
      payout: {
        bkash: 'bKash',
        nagad: 'Nagad',
        rocket: 'Rocket',
        bank: 'Bank',
      },
      region: {
        dhaka: 'Dhaka',
        chattogram: 'Chattogram',
        rajshahi: 'Rajshahi',
        khulna: 'Khulna',
        sylhet: 'Sylhet',
      },
      reportGenTitle: 'Report generation',
      reportGenLead: 'Download reports by program, region, and date range.',
      downloadFormat: 'Download {format}',
      reportTypeDisbursements: 'Program disbursements',
      reportTypeRegional: 'Regional impact',
      formatCsv: 'CSV',
      formatPdf: 'PDF',
      allPrograms: 'All programs',
      districtOptional: 'District (optional)',
      dateFrom: 'From',
      dateTo: 'To',
      fraudAwaitingReview: '{n} awaiting review',
      fraudAllClear: 'No duplicate aid flags. All clear.',
      fraudUnreviewed: 'Unreviewed',
      fraudConfirmed: 'Confirmed fraud',
      fraudCleared: 'Cleared',
      fraudReviewApplications: 'Review flagged applications',
      progStatus: {
        active: 'Active',
        draft: 'Draft',
        closed: 'Closed',
        pending: 'Pending',
      },
    },
  },
  bn: {
    common: {
      loading: 'লোড হচ্ছে…',
    },
    student: {
      programsTitle: 'উপলব্ধ বৃত্তি প্রোগ্রাম',
      loadingPrograms: 'প্রোগ্রাম লোড হচ্ছে…',
      loadError: 'প্রোগ্রাম লোড করা যায়নি',
      noOpen: 'এখন কোনো উন্মুক্ত প্রোগ্রাম নেই।',
      noOpenHint:
        'যদি আপনি সদ্য ডাটাবেস সেটআপ করেন, সিড স্ক্রিপ্ট চালান যাতে প্রদানকারী ও নমুনা বৃত্তি প্রোগ্রাম তৈরি হয়।',
      apply: 'আবেদন করুন',
      continueApplication: 'আবেদন চালিয়ে যান',
      applied: 'আবেদন করা হয়েছে',
      perBeneficiary: 'প্রতি উপকারভোগী ৳{n}',
      deadline: 'শেষ তারিখ',
      draftNote: 'খসড়া — সম্পন্ন ও প্রদানকারীর কাছে জমা দিন।',
      myAppsTitle: 'আমার আবেদন',
      noAppsLine: 'এখনও কোনো আবেদন নেই।',
      browseToApply: 'প্রোগ্রাম ব্রাউজ করুন',
      toApply: 'আবেদন করতে।',
      amount: 'অঙ্ক',
      started: 'শুরু',
      submittedOn: 'জমা',
      continueLink: 'আবেদন চালিয়ে যান',
      editLink: 'আবেদন সম্পাদনা',
      eligibility: 'যোগ্যতা',
      duplicateWarning: 'দ্বৈত সহায়তা সতর্কতা দেখা দিয়েছে।',
      draftBadge: 'খসড়া',
    },
    profile: {
      title: 'আমার প্রোফাইল',
      lead: 'তথ্য আপডেট রাখুন — এটি আপনার যোগ্য স্কোর ও সহায়তা আবেদনে সরাসরি প্রভাব ফেলে।',
      loadError: 'প্রোফাইল লোড করা যায়নি',
      updateError: 'আপডেট ব্যর্থ',
      saved: 'প্রোফাইল সফলভাবে সংরক্ষিত',
      savedUp: 'প্রোফাইল সেভ! যোগ্য স্কোর ↑ {diff} পয়েন্ট ({score}/১০০)',
      savedDown: 'প্রোফাইল সেভ। যোগ্য স্কোর ↓ {diff} পয়েন্ট ({score}/১০০)',
      loading: 'প্রোফাইল লোড হচ্ছে…',
      scoreTitle: 'যোগ্য স্কোর',
      scoreBlurb: 'আপনার স্কোর বিভিন্ন বিষয়ের ভিত্তিতে হিসাব করা হয়।',
      lastUpdated: 'সর্বশেষ হালনাগাদ',
      documents: 'নথি',
      ptsBonus: '(+{n} পয়েন্ট)',
      verified: 'যাচাইকৃত',
      rejected: 'প্রত্যাখ্যাত',
      unverified: 'অযাচাইকৃত',
      personalInfo: 'ব্যক্তিগত তথ্য',
      fullName: 'পূর্ণ নাম',
      phone: 'ফোন',
      gender: 'লিঙ্গ',
      select: '— বেছে নিন —',
      male: 'পুরুষ',
      female: 'মহিলা',
      location: 'অবস্থান',
      district: 'জেলা',
      upazila: 'উপজেলা',
      institution: 'প্রতিষ্ঠান',
      institutionName: 'প্রতিষ্ঠানের নাম',
      institutionType: 'প্রতিষ্ঠানের ধরন',
      school: 'স্কুল',
      college: 'কলেজ',
      university: 'বিশ্ববিদ্যালয়',
      financial: 'আর্থিক তথ্য',
      monthlyIncome: 'মাসিক পরিবারের আয় (বাংলাদেশী টাকা)',
      familySize: 'পরিবারের সদস্য সংখ্যা',
      academic: 'শৈক্ষিক কর্মক্ষমতা',
      attendance: 'উপস্থিতি %',
      cgpa: 'সিজিপিএ (০–৪)',
      saving: 'সংরক্ষণ ও স্কোর পুনঃগণনা…',
      save: 'পরিবর্তন সংরক্ষণ',
      scoreHigh: 'উচ্চ যোগ্যতা',
      scoreModerate: 'মাঝারি যোগ্যতা',
      scoreLow: 'নিম্ন যোগ্যতা',
      scoreNeedsData: 'আরো তথ্য দরকার',
    },
    nav: {
      home: 'হোম',
      howItWorks: 'কিভাবে কাজ করে',
      forStudents: 'শিক্ষার্থীদের জন্য',
      forProviders: 'প্রদানকারীদের জন্য',
      dashboard: 'ড্যাশবোর্ড',
      programs: 'প্রোগ্রাম',
      applications: 'আবেদন',
      reviewApplications: 'আবেদন পর্যালোচনা',
      profile: 'প্রোফাইল',
      students: 'শিক্ষার্থী',
      providers: 'প্রদানকারী',
      login: 'লগইন',
      register: 'নিবন্ধন',
      logout: 'লগআউট',
    },
    home: {
      title: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা',
      titleAccent: 'শিক্ষা সহায়তা',
      titleRest: ' বিতরণ ব্যবস্থা',
      subtitle: 'বাংলাদেশের মেধাবী শিক্ষার্থীদের যাচাইকৃত বৃত্তি প্রদানকারীদের সাথে সংযুক্ত করা। ন্যায়সঙ্গত, স্বচ্ছ এবং প্রভাবের জন্য নির্মিত।',
      applyStudent: 'শিক্ষার্থী হিসেবে আবেদন করুন',
      registerProvider: 'প্রদানকারী হিসেবে নিবন্ধন করুন',
      howItWorks: 'কিভাবে কাজ করে',
      students: 'শিক্ষার্থী',
      studentsDesc: 'শিক্ষাগত ও আর্থিক বিবরণ সহ আপনার প্রোফাইল তৈরি করুন। যোগ্য বৃত্তির সাথে মিলিত হন এবং এক জায়গায় আবেদন ট্র্যাক করুন।',
      providers: 'প্রদানকারী',
      providersDesc: 'এনজিও, ব্যাংক এবং দাতারা প্রোগ্রাম প্রকাশ করতে, মানদণ্ড নির্ধারণ করতে এবং সম্পূর্ণ স্বচ্ছতা ও দ্বৈত সহায়তা পরীক্ষা সহ তহবিল বিতরণ করতে পারেন।',
      transparency: 'স্বচ্ছতা',
      transparencyDesc: 'যোগ্যতা পরীক্ষা, প্রয়োজন ও মেধা অনুযায়ী র‍্যাংকিং এবং আঞ্চলিক বিশ্লেষণ জেলা ও উপজেলা জুড়ে সঠিক শিক্ষার্থীদের কাছে সহায়তা পৌঁছাতে নিশ্চিত করে।',
      getStarted: 'শুরু করুন',
      joinProvider: 'প্রদানকারী হিসেবে যোগ দিন',
      studentsSupported: 'সমর্থিত শিক্ষার্থী',
      verifiedProviders: 'যাচাইকৃত প্রদানকারী',
      nationwide: 'জাতীয় পর্যায়ে',
      districtCoverage: 'জেলা ও উপজেলা কভারেজ',
      readyTitle: 'শুরু করতে প্রস্তুত?',
      readyText: 'আপনার অ্যাকাউন্টে লগইন করুন বা আজই একটি তৈরি করুন।',
      registerStudent: 'শিক্ষার্থী হিসেবে নিবন্ধন',
      registerProviderLink: 'প্রদানকারী হিসেবে নিবন্ধন',
      dynamicFunding: 'গতিশীল অর্থায়ন',
      dynamicFundingDesc:
        'বাজেটকৃত প্রোগ্রামগুলো যোগ্য শিক্ষার্থীদের মধ্যে ন্যায়সঙ্গতভাবে সহায়তা বণ্টন করে।',
      impactTracking: 'প্রভাব নিরীক্ষণ',
      impactTrackingDesc:
        'প্রতিটি বিতরণ অবস্থার হালনাগাদ ও স্পষ্ট রিপোর্টের মাধ্যমে অনুসরণ করা হয়।',
      newHeroBadge: 'অত্যন্ত স্বচ্ছ অর্থায়ন',
      heroTitleHighlight: 'আলোকদার:',
      heroTitleRest: 'সকলের জন্য শিক্ষা নিশ্চিতকরণ',
      heroSubtitle:
        'মানব সম্ভাবনা ও শিক্ষাগত সুযোগের মাঝে সেতু – যাচাইযোগ্য, ব্লকচেইন-ভিত্তিক সহায়তা কাঠামোর মাধ্যমে। সৎ সহায়তা, সৎ বৃদ্ধি।',
      startApplication: 'আবেদন শুরু করুন',
      howWeVerify: 'আমরা কীভাবে যাচাই করি',
      demoGrantTitle: 'নতুন অনুদান জারি',
      demoGrantSubtitle: 'রফিক মিয়া ২,৪০০ ৳',
      heroImageAlt: 'পড়াশোনা করতে হাসিখুশি বাংলাদেশি শিক্ষার্থী',
      heroVerified: 'যাচাইকৃত',
      statStudentsAssisted: 'সহায়তাপ্রাপ্ত শিক্ষার্থী',
      statFundsDisbursed: 'বিতরিত তহবিল',
      statTransparencyRate: 'স্বচ্ছতার হার',
      conduitTitle: 'অগ্রগতির সোপান',
      conduitSubtitle: 'আবেদন থেকে অর্থবহ সহায়তা পর্যন্ত স্বচ্ছ, সুশৃঙ্খল পথ।',
      radicalTitle: 'স্বচ্ছতাই মানদণ্ড',
      radicalLead:
        'দাতা তহবিল থেকে শিক্ষার্থীর ফলাফল পর্যন্ত সহায়তা কীভাবে যায়, তা বাস্তব সময়ে দেখুন।',
      trustPoint1: 'তৃতীয় পক্ষের মান নিয়ন্ত্রণ',
      trustPoint2: 'প্রতিটি বিতরণে স্পষ্ট অডিট ট্রেইল',
      trustPoint3: 'লুকানো ফি ছাড়া বিতরণ মডেল',
      directFunding: 'সরাসরি অর্থায়ন',
      directFundingDesc: 'যাচাইকৃত চ্যানেলে শিক্ষার্থী ও প্রতিষ্ঠানে সহায়তা পৌঁছায়।',
      studentJourney: 'শিক্ষার্থীর যাত্রা',
      studentJourneyDesc: 'প্রথম আবেদন থেকে বৃত্তি সম্পন্ন পর্যন্ত অগ্রগতি দেখুন।',
      verificationAi: 'যাচাইকরণ (AI)',
      verificationAiDesc: 'পরিচয় ও যোগ্যতা পরীক্ষা প্রতারণা কমিয়ে আস্থা বাড়ায়।',
      globalSecurity: 'বিশ্বমানের নিরাপত্তা',
      globalSecurityDesc: 'আধুনিক সুরক্ষা শিক্ষার্থী ও প্রদানকারীর তথ্য রক্ষা করে।',
      ctaTitle: 'জীবন বদলাতে প্রস্তুত?',
      ctaText: 'আপনি শিক্ষার্থী হন বা দাতা, আপনার যাত্রা এখান থেকে।',
      getStartedToday: 'আজই শুরু করুন',
    },
    footer: {
      tagline: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা — বাংলাদেশের শিক্ষার্থীদের জন্য ন্যায়সঙ্গত ও স্বচ্ছ শিক্ষা সহায়তা।',
      students: 'শিক্ষার্থী',
      providers: 'প্রদানকারী',
      system: 'সিস্টেম',
      browsePrograms: 'প্রোগ্রাম ব্রাউজ করুন',
      copyright: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা। বাংলাদেশী শিক্ষার্থী ও বৃত্তি প্রদানকারীদের জন্য নির্মিত।',
    },
    help: {
      title: 'হেল্প সেন্টার',
      intro: 'EADS সম্পর্কে দ্রুত উত্তর এবং ব্যক্তিগত সহায়তা কীভাবে পাবেন।',
      faqSection: 'সাধারণ জিজ্ঞাসা',
      q1: 'আমি কীভাবে বৃত্তি প্রোগ্রামে আবেদন করব?',
      a1:
        'শিক্ষার্থী হিসেবে লগইন করুন, “সহায়তার জন্য আবেদন”-এ যান, একটি উন্মুক্ত প্রোগ্রাম বেছে নিয়ে প্রয়োজনীয় তথ্য ও নথি জমা দিন।',
      q2: 'আমার আবেদন এখনও ঝুলে আছে—কী করব?',
      a2:
        'ঝুলে থাকা মানে প্রদানকারী এখনও পর্যালোচনা করছে। আপনার প্রোফাইল ও নথি আপডেট রাখুন; অবস্থা বদলালে জানানো হবে।',
      q3: 'প্রদানকারীরা নতুন প্রোগ্রাম কীভাবে প্রকাশ করেন?',
      a3:
        'প্রদানকারী পোর্টালে “নতুন প্রোগ্রাম” দিয়ে বাজেট, যোগ্যতা ও আবেদনের সময়কাল ঠিক করুন।',
      q4: 'অ্যাকাউন্ট বা কারিগরি সমস্যায় কার সাথে যোগাযোগ করব?',
      a4: 'নিচের সহায়তা ইমেইল ব্যবহার করুন। প্রোগ্রাম-নির্দিষ্ট প্রশ্নে সংশ্লিষ্ট প্রদানকারীর সাহায্যও নিতে পারেন।',
      contactTitle: 'সহায়তা যোগাযোগ',
      contactLead: 'সাধারণত দুই কর্মদিবসের মধ্যে উত্তর দেওয়া হয়।',
      emailLabel: 'সহায়তা ইমেইল',
      copy: 'কপি',
      copyDone: 'কপি হয়েছে',
      copied: 'ক্লিপবোর্ডে কপি হয়েছে',
      openMail: 'ইমেইল অ্যাপে খুলুন',
    },
    rejections: {
      nav: 'প্রত্যাখ্যাত',
      providerTitle: 'প্রত্যাখ্যাত আবেদন',
      adminTitle: 'প্রত্যাখ্যাত তালিকা',
      leadProvider: 'আপনার প্রতিষ্ঠান কোন প্রোগ্রামে কোন শিক্ষার্থীকে প্রত্যাখ্যান করেছে। অন্য আবেদন পর্যালোচনা করতে প্রোগ্রামে যান।',
      leadAdmin: 'প্রদানকারীর আবেদন অস্বীকার ও প্রোফাইল যাচাইকরণে প্রত্যাখ্যাত শিক্ষার্থীরা।',
      emptyApps: 'আপনার প্রোগ্রামে কোনো প্রত্যাখ্যাত আবেদন নেই।',
      emptyAppsAdmin: 'সিস্টেমে কোনো প্রত্যাখ্যাত আবেদন এখনও নেই।',
      emptyProfile: 'প্রোফাইলে প্রত্যাখ্যাত এমন কোনো শিক্ষার্থী নেই।',
      applicationSection: 'আবেদন প্রত্যাখ্যাত',
      profileSection: 'প্রোফাইল যাচাই — প্রত্যাখ্যাত',
      student: 'শিক্ষার্থী',
      program: 'প্রোগ্রাম',
      provider: 'প্রদানকারী',
      email: 'ইমেইল',
      reason: 'কারণ',
      reviewed: 'পর্যালোচনার তারিখ',
      notProvided: '—',
      openProgram: 'প্রোগ্রামের আবেদন',
      openStudent: 'শিক্ষার্থী দেখুন',
    },
    dash: {
      studentPortal: 'শিক্ষার্থী পোর্টাল',
      providerPortal: 'প্রতিষ্ঠান পোর্টাল',
      adminPortal: 'প্রশাসন',
      systemTagline: 'শিক্ষা সহায়তা ব্যবস্থা',
      applyForAid: 'সহায়তার জন্য আবেদন',
      disbursementStatus: 'বিতরণ অবস্থা',
      notifications: 'বিজ্ঞপ্তি',
      newProgram: 'নতুন প্রোগ্রাম',
      reviewApplicationsLead:
        'নিচে একটি প্রোগ্রাম বেছে তার সারি খুলুন। আপনার প্রতিষ্ঠানে জমা দেওয়া আবেদন অনুমোদন বা প্রত্যাখ্যান করুন।',
      systemAnalytics: 'সিস্টেম বিশ্লেষণ',
      settings: 'সেটিংস',
      needSupport: 'সহায়তা দরকার?',
      helpCenter: 'হেল্প সেন্টার',
      welcomeBack: 'স্বাগতম',
      systemOverview: 'শিক্ষা সহায়তা বিতরণ ও যাচাইকরণের সংক্ষিপ্ত চিত্র।',
      profileCard: 'প্রোফাইল',
      applicationStatus: 'আবেদনের অবস্থা',
      eligibilityScore: 'প্রয়োজন ও মেধা সূচক',
      recentApplications: 'সাম্প্রতিক আবেদন',
      activeScholarships: 'আবেদনের সারাংশ',
      academicInsight: 'আপনার প্রোফাইল অন্তর্দৃষ্টি',
      insightBody:
        'উপস্থিতি, সিজিপিএ এবং আর্থিক প্রয়োজনের ভিত্তিতে, নতুন প্রোগ্রামের জন্য যোগ্য থাকতে নথি যাচাইকৃত রাখুন।',
      explorePrograms: 'প্রোগ্রাম দেখুন',
      totalPrograms: 'প্রোগ্রাম',
      totalDisbursedLabel: 'মোট বিতরণ (সব প্রোগ্রাম)',
      activeScholars: 'সক্রিয় উপকারভোগী',
      programProgress: 'প্রোগ্রাম তহবিল',
      impactNote: 'স্বচ্ছ ট্র্যাকিং নিশ্চিত করে যে সহায়তা যাচাইকৃত শিক্ষার্থীদের কাছে পৌঁছায়।',
      verificationCard: 'যাচাইকরণ',
      verificationBody:
        'আয়ের প্রমাণ ও ট্রান্সক্রিপ্ট আপডেট রাখুন যাতে প্রদানকারী দ্রুত আবেদন পর্যালোচনা করতে পারে।',
      distributionByRegion: 'আঞ্চলিক কার্যক্রম (নমুনা)',
      approvalRatio: 'আবেদন ধারা',
      approved: 'অনুমোদিত',
      rejected: 'প্রত্যাখ্যাত',
      pending: 'অপেক্ষমাণ',
      duplicateAlerts: 'দ্বৈত সহায়তা পরীক্ষা',
      duplicateBody: 'প্রশাসকদের পর্যালোচনার জন্য সিস্টেম ওভারল্যাপিং অনুমোদন চিহ্নিত করে।',
      quickActions: 'দ্রুত কাজ',
      verifyStudents: 'শিক্ষার্থী পর্যালোচনা',
      approveProviders: 'প্রদানকারী পর্যালোচনা',
      disbursements: 'বিতরণ',
      impactReport: 'রিপোর্ট',
      recentDisbursements: 'সাম্প্রতিক কার্যক্রম',
      pendingProviders: 'প্রদানকারী তদারকি',
      securityCard: 'অডিট ও নিরাপত্তা',
      securityBody: 'স্বচ্ছতার জন্য গুরুত্বপূর্ণ কাজগুলো লগ করা হয়।',
      generateExport: 'এক্সপোর্ট তৈরি',
      reportPeriod: 'সর্বশেষ সারাংশ',
      attendanceShort: 'উপস্থিতি',
      totalAid: 'মোট প্রাপ্ত সহায়তা',
      needLabel: 'প্রয়োজন স্কোর',
      stepProfile: 'প্রোফাইল ও নথি',
      stepApply: 'আবেদন',
      stepDecision: 'সিদ্ধান্ত',
      submitted: 'জমা দেওয়া',
      noApplicationsYet: 'এখনও কোনো আবেদন নেই।',
      pendingLower: 'পর্যালোচনাধীন',
      approvedLower: 'অনুমোদিত',
      eligibilityBlurb: 'উচ্চ স্কোর মেধা সূচকের তুলনায় বেশি আর্থিক প্রয়োজন নির্দেশ করে।',
      compositeIndex: 'সমন্বিত সূচক (০–১০০)',
      noNotifications: 'কোনো নতুন বিজ্ঞপ্তি নেই।',
      markAllRead: 'সব পঠিত হিসেবে চিহ্নিত করুন',
      cancel: 'বাতিল',
      rejectAppTitle: 'আবেদন প্রত্যাখ্যান',
      rejectAppLead: 'আবেদনকারীকে জানানো হবে। সিদ্ধান্তের কারণ নোট (ঐচ্ছিক) যোগ করতে পারেন।',
      rejectAppStudent: 'আবেদনকারী',
      rejectAppReason: 'কারণ (ঐচ্ছিক)',
      confirmReject: 'প্রত্যাখ্যান নিশ্চিত',
      working: 'কাজ চলছে…',
      withdrawFunds: 'ব্যালান্স উত্তোলন',
      withdrawNoBalance: 'এখনও উত্তোলনযোগ্য ব্যালান্স নেই।',
      withdrawTitle: 'আপনার অ্যাকাউন্টে উত্তোলন',
      withdrawAvailable: 'উপলব্ধ ব্যালান্স:',
      withdrawMethod: 'পেআউট পদ্ধতি',
      withdrawAmount: 'অঙ্ক (বাংলাদেশী টাকা)',
      withdrawWalletNumber: 'মোবাইল ওয়ালেট নম্বর',
      withdrawBankName: 'ব্যাংকের নাম',
      withdrawAccountName: 'অ্যাকাউন্টধারীর নাম',
      withdrawAccountNumber: 'অ্যাকাউন্ট নম্বর',
      withdrawBranch: 'শাখা (ঐচ্ছিক)',
      withdrawRouting: 'রাউটিং নম্বর (ঐচ্ছিক)',
      withdrawNote:
        'আপনি যে তথ্য দেবেন সেখানে টাকা পাঠানো হবে। নম্বর বা ব্যাংক অ্যাকাউন্ট সঠিক কিনা নিশ্চিত করুন।',
      withdrawInvalidAmount: 'বৈধ পূর্ণ টাকার অঙ্ক দিন (কমপক্ষে ৳১)।',
      withdrawExceedsBalance: 'এই অঙ্ক আপনার উপলব্ধ ব্যালান্সের চেয়ে বেশি।',
      submitWithdrawal: 'উত্তোলন জমা দিন',
      withdrawSuccess: 'উত্তোলনের অনুরোধ জমা হয়েছে।',
      withdrawError: 'উত্তোলন জমা দেওয়া যায়নি।',
      withdrawHistory: 'উত্তোলনের অনুরোধ',
      noWithdrawals: 'এখনও কোনো উত্তোলনের অনুরোধ নেই।',
      disburseModalTitle: 'বিতরণ রেকর্ড করুন',
      disburseModalLead:
        'এই অনুমোদিত আবেদনের জন্য তহবিল নিশ্চিত করুন। এটি প্রোগ্রাম বাজেট আপডেট করে এবং শিক্ষার্থীর ব্যালান্সে জমা ধরে।',
      disburseAmount: 'অঙ্ক (বাংলাদেশী টাকা)',
      disburseMethod: 'পেমেন্ট পদ্ধতি',
      disburseRef: 'লেনদেন রেফারেন্স',
      disburseReleaseDate: 'রিলিজের তারিখ',
      disburseConfirm: 'নিশ্চিত ও রেকর্ড করুন',
      disburseStudent: 'শিক্ষার্থী',
      disburseProgram: 'প্রোগ্রাম',
      disburseDefault: 'পূর্বনির্ধারিত অঙ্ক',
      disburseFundLeft: 'প্রোগ্রামে অবশিষ্ট তহবিল',
      noDisbursements: 'এখনও কোনো বিতরণ রেকর্ড নেই।',
      providerLead:
        'বৃত্তি প্রোগ্রাম কনফিগার করুন এবং যাচাইকৃত শিক্ষার্থীদের কাছে তহবিল কীভাবে যায় তা দেখুন।',
      createProgramTitle: 'প্রোগ্রাম ও তহবিল',
      createProgramSub: 'স্পষ্ট বাজেট ও উপকারভোগী সীমা সহ নতুন সহায়তা চক্র শুরু করুন।',
      createProgramHint:
        'প্রতি শিক্ষার্থীর অঙ্ক, সর্বোচ্চ উপকারভোগী এবং যোগ্যতা নির্ধারণে “নতুন প্রোগ্রাম” ব্যবহার করুন।',
      activePrograms: 'সক্রিয়',
      viewAll: 'সব দেখুন',
      noProgramsYet: 'এখনও কোনো প্রোগ্রাম নেই। আবেদন গ্রহণ শুরু করতে একটি তৈরি করুন।',
      beneficiaryLine: 'উপকারভোগী',
      disbursedShort: 'বিতরিত',
      totalShort: 'মোট',
      transparencyTitle: 'ন্যায়সঙ্গত, ট্রেসযোগ্য বিতরণ',
      atRiskBadge: 'ঝুঁকিতে',
      loading: 'ড্যাশবোর্ড লোড হচ্ছে…',
      exportSoon: 'এক্সপোর্টে বর্তমান ফিল্টার অন্তর্ভুক্ত হবে (শীঘ্রই)।',
      pendingQueue: 'পর্যালোচনায়',
      duplicateHint: 'আবেদন ও বিতরণ মডিউল থেকে ওভারল্যাপিং অনুমোদন পর্যালোচনা করুন।',
      totalStudents: 'শিক্ষার্থী',
      totalProviders: 'প্রদানকারী',
      auditLog: 'অডিট ট্রেইল',
      colAction: 'কাজ',
      colResource: 'রিসোর্স',
      colUser: 'ব্যবহারকারী',
      colTime: 'সময়',
      activeProgramsLabel: 'সক্রিয় প্রোগ্রাম',
      fraudReview: 'প্রতারণা পর্যালোচনা',
      disburseAid: 'সহায়তা বিতরণ',
      cgpaLabel: 'সিজিপিএ',
      accountBalance: 'অ্যাকাউন্ট ব্যালান্স',
      unverified: 'অযাচাইকৃত',
      downloadReport: 'রিপোর্ট ডাউনলোড (পিডিএফ)',
      downloading: 'ডাউনলোড হচ্ছে…',
      idLabel: 'আইডি',
      reportDownloaded: 'রিপোর্ট ডাউনলোড হয়েছে',
      reportFailed: 'রিপোর্ট তৈরি ব্যর্থ',
      reportFailedGen: 'রিপোর্ট তৈরি করা যায়নি',
      downloadReportError: 'রিপোর্ট ডাউনলোডে ত্রুটি',
      themeLight: 'আলো মোড',
      themeDark: 'ডার্ক মোড',
      navOpen: 'নেভিগেশন খুলুন',
      navClose: 'নেভিগেশন বন্ধ করুন',
      navExpand: 'সাইডবার প্রসারিত করুন',
      navCollapse: 'সাইডবার সঙ্কুচিত করুন',
      appStatus: {
        pending: 'অপেক্ষমাণ',
        approved: 'অনুমোদিত',
        rejected: 'প্রত্যাখ্যাত',
      },
      disbStatus: {
        completed: 'সম্পন্ন',
        pending: 'অপেক্ষমাণ',
        failed: 'ব্যর্থ',
        processing: 'প্রক্রিয়াকরণ',
      },
      payout: {
        bkash: 'বিকাশ',
        nagad: 'নগদ',
        rocket: 'রকেট',
        bank: 'ব্যাংক',
      },
      region: {
        dhaka: 'ঢাকা',
        chattogram: 'চট্টগ্রাম',
        rajshahi: 'রাজশাহী',
        khulna: 'খুলনা',
        sylhet: 'সিলেট',
      },
      reportGenTitle: 'রিপোর্ট তৈরি',
      reportGenLead: 'প্রোগ্রাম, অঞ্চল ও তারিখের ভিত্তিতে রিপোর্ট ডাউনলোড করুন।',
      downloadFormat: '{format} ডাউনলোড',
      reportTypeDisbursements: 'প্রোগ্রাম বিতরণ',
      reportTypeRegional: 'আঞ্চলিক প্রভাব',
      formatCsv: 'সিএসভি',
      formatPdf: 'পিডিএফ',
      allPrograms: 'সব প্রোগ্রাম',
      districtOptional: 'জেলা (ঐচ্ছিক)',
      dateFrom: 'শুরু',
      dateTo: 'শেষ',
      fraudAwaitingReview: '{n}টি পর্যালোচনার অপেক্ষায়',
      fraudAllClear: 'কোনো দ্বৈত সহায়তা ফ্ল্যাগ নেই। সব ঠিক।',
      fraudUnreviewed: 'অপর্যালোচিত',
      fraudConfirmed: 'নিশ্চিত প্রতারণা',
      fraudCleared: 'মোক্ত',
      fraudReviewApplications: 'চিহ্নিত আবেদন দেখুন',
      progStatus: {
        active: 'সক্রিয়',
        draft: 'খসড়া',
        closed: 'বন্ধ',
        pending: 'অপেক্ষমাণ',
      },
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return localStorage.getItem(STORAGE_KEY) || 'en';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = (key) => {
    const keys = key.split('.');
    const walk = (root) => {
      let v = root;
      for (const k of keys) {
        v = v?.[k];
      }
      return v;
    };
    const primary = walk(translations[lang]);
    if (primary !== undefined && primary !== null) return primary;
    const fallback = walk(translations.en);
    if (fallback !== undefined && fallback !== null) return fallback;
    return key;
  };

  const toggleLanguage = () => setLang((l) => (l === 'en' ? 'bn' : 'en'));

  const locale = lang === 'bn' ? 'bn-BD' : 'en-GB';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage, locale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
