import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const STORAGE_KEY = 'eads_lang';

const translations = {
  en: {
    nav: {
      home: 'Home',
      howItWorks: 'How it works',
      forStudents: 'For Students',
      forProviders: 'For Providers',
      dashboard: 'Dashboard',
      programs: 'Programs',
      applications: 'Applications',
      reviewApplications: 'Review applications',
      profile: 'Profile',
      students: 'Students',
      providers: 'Providers',
      login: 'Log in',
      register: 'Register',
      logout: 'Logout',
    },
    home: {
      title: 'Education Aid Disbursement System',
      titleAccent: 'Education Aid',
      titleRest: ' Disbursement System',
      subtitle: 'Connecting talented students in Bangladesh with verified scholarship providers. Fair, transparent, and built for impact.',
      applyStudent: 'Apply as Student',
      registerProvider: 'Register as Provider',
      howItWorks: 'How it works',
      students: 'Students',
      studentsDesc: 'Create your profile with academic and financial details. Get matched to eligible scholarships and track applications in one place.',
      providers: 'Providers',
      providersDesc: 'NGOs, banks, and donors can publish programs, set criteria, and disburse funds with full transparency and duplicate-aid checks.',
      transparency: 'Transparency',
      transparencyDesc: 'Eligibility checks, ranking by need and merit, and regional analytics ensure aid reaches the right students across districts and upazilas.',
      getStarted: 'Get started',
      joinProvider: 'Join as provider',
      studentsSupported: 'Students supported',
      verifiedProviders: 'Verified providers',
      nationwide: 'Nationwide',
      districtCoverage: 'District & upazila coverage',
      readyTitle: 'Ready to get started?',
      readyText: 'Log in to your account or create one today.',
      registerStudent: 'Register as student',
      registerProviderLink: 'Register as provider',
    },
    footer: {
      tagline: 'Education Aid Disbursement System — fair and transparent educational aid for students in Bangladesh.',
      students: 'Students',
      providers: 'Providers',
      system: 'System',
      browsePrograms: 'Browse programs',
      copyright: 'Education Aid Disbursement System. Built for Bangladeshi students and scholarship providers.',
    },
    help: {
      title: 'Help center',
      intro: 'Quick answers about EADS and how to get personal support.',
      faqSection: 'Common questions',
      q1: 'How do I apply for a scholarship program?',
      a1:
        'Log in as a student, go to “Apply for aid”, choose an open program, and submit the required details and documents.',
      q2: 'My application is still pending. What should I do?',
      a2:
        'Pending means the provider is reviewing your application. Keep your profile and documents up to date; you will be notified when the status changes.',
      q3: 'How do providers publish new programs?',
      a3:
        'In the provider portal, use “New program” to set the budget, eligibility rules, and application window for verified students.',
      q4: 'Who do I contact for account or technical problems?',
      a4: 'Use the support email below. For program-specific questions, you can also reach out to the provider running that scholarship.',
      contactTitle: 'Contact support',
      contactLead: 'We usually respond within two business days.',
      emailLabel: 'Support email',
      copy: 'Copy',
      copyDone: 'Copied',
      copied: 'Copied to clipboard',
      openMail: 'Open in email',
    },
    rejections: {
      nav: 'Rejections',
      providerTitle: 'Rejected applications',
      adminTitle: 'Rejections',
      leadProvider: 'Students your organization declined for a program. You can return to a program to review other applicants at any time.',
      leadAdmin: 'Application denials from providers and profile verification rejections by administrators.',
      emptyApps: 'No rejected applications on record for your programs.',
      emptyAppsAdmin: 'No rejected applications in the system yet.',
      emptyProfile: 'No students with rejected profile verification.',
      applicationSection: 'Application rejections',
      profileSection: 'Profile verification rejections',
      student: 'Student',
      program: 'Program',
      provider: 'Provider',
      email: 'Email',
      reason: 'Reason',
      reviewed: 'Reviewed',
      notProvided: '—',
      openProgram: 'Program applications',
      openStudent: 'View student',
    },
    dash: {
      studentPortal: 'Student portal',
      providerPortal: 'Institutional portal',
      adminPortal: 'Administration',
      systemTagline: 'Education Aid System',
      applyForAid: 'Apply for aid',
      disbursementStatus: 'Disbursement status',
      notifications: 'Notifications',
      newProgram: 'New program',
      reviewApplicationsLead:
        'Choose a program below to open its queue. Approve or reject applications that students have submitted to your organization.',
      systemAnalytics: 'System analytics',
      settings: 'Settings',
      needSupport: 'Need support?',
      helpCenter: 'Help center',
      welcomeBack: 'Welcome back',
      systemOverview: 'Overview of education aid distribution and verification.',
      profileCard: 'Profile',
      applicationStatus: 'Application status',
      eligibilityScore: 'Need & merit index',
      recentApplications: 'Recent applications',
      activeScholarships: 'Applications overview',
      academicInsight: 'Your profile insight',
      insightBody:
        'Based on your attendance, CGPA, and financial need score, keep your documents verified to stay eligible for new programs.',
      explorePrograms: 'Explore programs',
      totalPrograms: 'Programs',
      totalDisbursedLabel: 'Total disbursed (all programs)',
      activeScholars: 'Active beneficiaries',
      programProgress: 'Program funding',
      impactNote: 'Transparent tracking helps ensure aid reaches verified students on time.',
      verificationCard: 'Verification',
      verificationBody:
        'Keep income proof and transcripts up to date so providers can review your application faster.',
      distributionByRegion: 'Regional activity (illustrative)',
      approvalRatio: 'Application pipeline',
      approved: 'Approved',
      rejected: 'Rejected',
      pending: 'Pending',
      duplicateAlerts: 'Duplicate aid checks',
      duplicateBody: 'The system flags overlapping approvals so administrators can review conflicts.',
      quickActions: 'Quick actions',
      verifyStudents: 'Review students',
      approveProviders: 'Review providers',
      disbursements: 'Disbursements',
      impactReport: 'Reports',
      recentDisbursements: 'Recent activity',
      pendingProviders: 'Provider oversight',
      securityCard: 'Audit & security',
      securityBody: 'Important actions are logged for transparency and accountability.',
      generateExport: 'Generate export',
      reportPeriod: 'Latest summary',
      attendanceShort: 'Attendance',
      totalAid: 'Total aid received',
      needLabel: 'Need score',
      stepProfile: 'Profile & documents',
      stepApply: 'Applications',
      stepDecision: 'Decisions',
      submitted: 'submitted',
      noApplicationsYet: 'No applications yet.',
      pendingLower: 'pending review',
      approvedLower: 'approved',
      eligibilityBlurb: 'Higher scores reflect greater financial need relative to merit indicators.',
      compositeIndex: 'Composite index (0–100)',
      noNotifications: 'No new notifications.',
      markAllRead: 'Mark all as read',
      cancel: 'Cancel',
      rejectAppTitle: 'Reject application',
      rejectAppLead: 'The applicant will be notified. You may add an optional note explaining the decision.',
      rejectAppStudent: 'Applicant',
      rejectAppReason: 'Reason (optional)',
      confirmReject: 'Confirm rejection',
      working: 'Working…',
      withdrawFunds: 'Withdraw balance',
      withdrawNoBalance: 'No available balance to withdraw yet.',
      withdrawTitle: 'Withdraw to your account',
      withdrawAvailable: 'Available balance:',
      withdrawMethod: 'Payout method',
      withdrawAmount: 'Amount (BDT)',
      withdrawWalletNumber: 'Mobile wallet number',
      withdrawBankName: 'Bank name',
      withdrawAccountName: 'Account holder name',
      withdrawAccountNumber: 'Account number',
      withdrawBranch: 'Branch (optional)',
      withdrawRouting: 'Routing number (optional)',
      withdrawNote:
        'Funds will be sent to the details you provide. Ensure your number or bank account is correct.',
      submitWithdrawal: 'Submit withdrawal',
      withdrawSuccess: 'Withdrawal request submitted.',
      withdrawError: 'Could not submit withdrawal.',
      withdrawHistory: 'Withdrawal requests',
      noWithdrawals: 'No withdrawal requests yet.',
      disburseModalTitle: 'Record disbursement',
      disburseModalLead:
        'Confirm funds for this approved application. This updates the program budget and credits the student.',
      disburseAmount: 'Amount (BDT)',
      disburseMethod: 'Payment method',
      disburseRef: 'Transaction reference',
      disburseReleaseDate: 'Release date',
      disburseConfirm: 'Confirm & record',
      disburseStudent: 'Student',
      disburseProgram: 'Program',
      disburseDefault: 'Default amount',
      disburseFundLeft: 'Program fund remaining',
      noDisbursements: 'No disbursements recorded yet.',
      providerLead:
        'Configure scholarship programs and monitor how funds move to verified students.',
      createProgramTitle: 'Programs & funding',
      createProgramSub: 'Launch a new aid cycle with clear budget and beneficiary limits.',
      createProgramHint:
        'Use “New program” to set amount per student, maximum beneficiaries, and eligibility.',
      activePrograms: 'active',
      viewAll: 'View all',
      noProgramsYet: 'No programs yet. Create one to start receiving applications.',
      beneficiaryLine: 'Beneficiaries',
      disbursedShort: 'disbursed',
      totalShort: 'total',
      transparencyTitle: 'Fair, traceable disbursements',
      atRiskBadge: 'At-risk',
      loading: 'Loading dashboard…',
      exportSoon: 'Export will include current filters (coming soon).',
      pendingQueue: 'Pending review',
      duplicateHint: 'Review overlapping approvals from the Applications and Disbursements modules.',
      totalStudents: 'students',
      totalProviders: 'providers',
      auditLog: 'Audit trail',
      colAction: 'Action',
      colResource: 'Resource',
      colUser: 'User',
      colTime: 'Time',
      activeProgramsLabel: 'Active programs',
      region: {
        dhaka: 'Dhaka',
        chattogram: 'Chattogram',
        rajshahi: 'Rajshahi',
        khulna: 'Khulna',
        sylhet: 'Sylhet',
      },
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      howItWorks: 'কিভাবে কাজ করে',
      forStudents: 'শিক্ষার্থীদের জন্য',
      forProviders: 'প্রদানকারীদের জন্য',
      dashboard: 'ড্যাশবোর্ড',
      programs: 'প্রোগ্রাম',
      applications: 'আবেদন',
      reviewApplications: 'আবেদন পর্যালোচনা',
      profile: 'প্রোফাইল',
      students: 'শিক্ষার্থী',
      providers: 'প্রদানকারী',
      login: 'লগইন',
      register: 'নিবন্ধন',
      logout: 'লগআউট',
    },
    home: {
      title: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা',
      titleAccent: 'শিক্ষা সহায়তা',
      titleRest: ' বিতরণ ব্যবস্থা',
      subtitle: 'বাংলাদেশের মেধাবী শিক্ষার্থীদের যাচাইকৃত বৃত্তি প্রদানকারীদের সাথে সংযুক্ত করা। ন্যায়সঙ্গত, স্বচ্ছ এবং প্রভাবের জন্য নির্মিত।',
      applyStudent: 'শিক্ষার্থী হিসেবে আবেদন করুন',
      registerProvider: 'প্রদানকারী হিসেবে নিবন্ধন করুন',
      howItWorks: 'কিভাবে কাজ করে',
      students: 'শিক্ষার্থী',
      studentsDesc: 'শিক্ষাগত ও আর্থিক বিবরণ সহ আপনার প্রোফাইল তৈরি করুন। যোগ্য বৃত্তির সাথে মিলিত হন এবং এক জায়গায় আবেদন ট্র্যাক করুন।',
      providers: 'প্রদানকারী',
      providersDesc: 'এনজিও, ব্যাংক এবং দাতারা প্রোগ্রাম প্রকাশ করতে, মানদণ্ড নির্ধারণ করতে এবং সম্পূর্ণ স্বচ্ছতা ও দ্বৈত সহায়তা পরীক্ষা সহ তহবিল বিতরণ করতে পারেন।',
      transparency: 'স্বচ্ছতা',
      transparencyDesc: 'যোগ্যতা পরীক্ষা, প্রয়োজন ও মেধা অনুযায়ী র‍্যাংকিং এবং আঞ্চলিক বিশ্লেষণ জেলা ও উপজেলা জুড়ে সঠিক শিক্ষার্থীদের কাছে সহায়তা পৌঁছাতে নিশ্চিত করে।',
      getStarted: 'শুরু করুন',
      joinProvider: 'প্রদানকারী হিসেবে যোগ দিন',
      studentsSupported: 'সমর্থিত শিক্ষার্থী',
      verifiedProviders: 'যাচাইকৃত প্রদানকারী',
      nationwide: 'জাতীয় পর্যায়ে',
      districtCoverage: 'জেলা ও উপজেলা কভারেজ',
      readyTitle: 'শুরু করতে প্রস্তুত?',
      readyText: 'আপনার অ্যাকাউন্টে লগইন করুন বা আজই একটি তৈরি করুন।',
      registerStudent: 'শিক্ষার্থী হিসেবে নিবন্ধন',
      registerProviderLink: 'প্রদানকারী হিসেবে নিবন্ধন',
    },
    footer: {
      tagline: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা — বাংলাদেশের শিক্ষার্থীদের জন্য ন্যায়সঙ্গত ও স্বচ্ছ শিক্ষা সহায়তা।',
      students: 'শিক্ষার্থী',
      providers: 'প্রদানকারী',
      system: 'সিস্টেম',
      browsePrograms: 'প্রোগ্রাম ব্রাউজ করুন',
      copyright: 'শিক্ষা সহায়তা বিতরণ ব্যবস্থা। বাংলাদেশী শিক্ষার্থী ও বৃত্তি প্রদানকারীদের জন্য নির্মিত।',
    },
    help: {
      title: 'হেল্প সেন্টার',
      intro: 'EADS সম্পর্কে দ্রুত উত্তর এবং ব্যক্তিগত সহায়তা কীভাবে পাবেন।',
      faqSection: 'সাধারণ জিজ্ঞাসা',
      q1: 'আমি কীভাবে বৃত্তি প্রোগ্রামে আবেদন করব?',
      a1:
        'শিক্ষার্থী হিসেবে লগইন করুন, “সহায়তার জন্য আবেদন”-এ যান, একটি উন্মুক্ত প্রোগ্রাম বেছে নিয়ে প্রয়োজনীয় তথ্য ও নথি জমা দিন।',
      q2: 'আমার আবেদন এখনও ঝুলে আছে—কী করব?',
      a2:
        'ঝুলে থাকা মানে প্রদানকারী এখনও পর্যালোচনা করছে। আপনার প্রোফাইল ও নথি আপডেট রাখুন; অবস্থা বদলালে জানানো হবে।',
      q3: 'প্রদানকারীরা নতুন প্রোগ্রাম কীভাবে প্রকাশ করেন?',
      a3:
        'প্রদানকারী পোর্টালে “নতুন প্রোগ্রাম” দিয়ে বাজেট, যোগ্যতা ও আবেদনের সময়কাল ঠিক করুন।',
      q4: 'অ্যাকাউন্ট বা কারিগরি সমস্যায় কার সাথে যোগাযোগ করব?',
      a4: 'নিচের সহায়তা ইমেইল ব্যবহার করুন। প্রোগ্রাম-নির্দিষ্ট প্রশ্নে সংশ্লিষ্ট প্রদানকারীর সাহায্যও নিতে পারেন।',
      contactTitle: 'সহায়তা যোগাযোগ',
      contactLead: 'সাধারণত দুই কর্মদিবসের মধ্যে উত্তর দেওয়া হয়।',
      emailLabel: 'সহায়তা ইমেইল',
      copy: 'কপি',
      copyDone: 'কপি হয়েছে',
      copied: 'ক্লিপবোর্ডে কপি হয়েছে',
      openMail: 'ইমেইল অ্যাপে খুলুন',
    },
    rejections: {
      nav: 'প্রত্যাখ্যাত',
      providerTitle: 'প্রত্যাখ্যাত আবেদন',
      adminTitle: 'প্রত্যাখ্যাত তালিকা',
      leadProvider: 'আপনার প্রতিষ্ঠান কোন প্রোগ্রামে কোন শিক্ষার্থীকে প্রত্যাখ্যান করেছে। অন্য আবেদন পর্যালোচনা করতে প্রোগ্রামে যান।',
      leadAdmin: 'প্রদানকারীর আবেদন অস্বীকার ও প্রোফাইল যাচাইকরণে প্রত্যাখ্যাত শিক্ষার্থীরা।',
      emptyApps: 'আপনার প্রোগ্রামে কোনো প্রত্যাখ্যাত আবেদন নেই।',
      emptyAppsAdmin: 'সিস্টেমে কোনো প্রত্যাখ্যাত আবেদন এখনও নেই।',
      emptyProfile: 'প্রোফাইলে প্রত্যাখ্যাত এমন কোনো শিক্ষার্থী নেই।',
      applicationSection: 'আবেদন প্রত্যাখ্যাত',
      profileSection: 'প্রোফাইল যাচাই — প্রত্যাখ্যাত',
      student: 'শিক্ষার্থী',
      program: 'প্রোগ্রাম',
      provider: 'প্রদানকারী',
      email: 'ইমেইল',
      reason: 'কারণ',
      reviewed: 'পর্যালোচনার তারিখ',
      notProvided: '—',
      openProgram: 'প্রোগ্রামের আবেদন',
      openStudent: 'শিক্ষার্থী দেখুন',
    },
    dash: {
      studentPortal: 'শিক্ষার্থী পোর্টাল',
      providerPortal: 'প্রতিষ্ঠান পোর্টাল',
      adminPortal: 'প্রশাসন',
      systemTagline: 'শিক্ষা সহায়তা ব্যবস্থা',
      applyForAid: 'সহায়তার জন্য আবেদন',
      disbursementStatus: 'বিতরণ অবস্থা',
      notifications: 'বিজ্ঞপ্তি',
      newProgram: 'নতুন প্রোগ্রাম',
      reviewApplicationsLead:
        'নিচে একটি প্রোগ্রাম বেছে তার সারি খুলুন। আপনার প্রতিষ্ঠানে জমা দেওয়া আবেদন অনুমোদন বা প্রত্যাখ্যান করুন।',
      systemAnalytics: 'সিস্টেম বিশ্লেষণ',
      settings: 'সেটিংস',
      needSupport: 'সহায়তা দরকার?',
      helpCenter: 'হেল্প সেন্টার',
      welcomeBack: 'স্বাগতম',
      systemOverview: 'শিক্ষা সহায়তা বিতরণ ও যাচাইকরণের সংক্ষিপ্ত চিত্র।',
      profileCard: 'প্রোফাইল',
      applicationStatus: 'আবেদনের অবস্থা',
      eligibilityScore: 'প্রয়োজন ও মেধা সূচক',
      recentApplications: 'সাম্প্রতিক আবেদন',
      activeScholarships: 'আবেদনের সারাংশ',
      academicInsight: 'আপনার প্রোফাইল অন্তর্দৃষ্টি',
      insightBody:
        'উপস্থিতি, সিজিপিএ এবং আর্থিক প্রয়োজনের ভিত্তিতে, নতুন প্রোগ্রামের জন্য যোগ্য থাকতে নথি যাচাইকৃত রাখুন।',
      explorePrograms: 'প্রোগ্রাম দেখুন',
      totalPrograms: 'প্রোগ্রাম',
      totalDisbursedLabel: 'মোট বিতরণ (সব প্রোগ্রাম)',
      activeScholars: 'সক্রিয় উপকারভোগী',
      programProgress: 'প্রোগ্রাম তহবিল',
      impactNote: 'স্বচ্ছ ট্র্যাকিং নিশ্চিত করে যে সহায়তা যাচাইকৃত শিক্ষার্থীদের কাছে পৌঁছায়।',
      verificationCard: 'যাচাইকরণ',
      verificationBody:
        'আয়ের প্রমাণ ও ট্রান্সক্রিপ্ট আপডেট রাখুন যাতে প্রদানকারী দ্রুত আবেদন পর্যালোচনা করতে পারে।',
      distributionByRegion: 'আঞ্চলিক কার্যক্রম (নমুনা)',
      approvalRatio: 'আবেদন ধারা',
      approved: 'অনুমোদিত',
      rejected: 'প্রত্যাখ্যাত',
      pending: 'অপেক্ষমাণ',
      duplicateAlerts: 'দ্বৈত সহায়তা পরীক্ষা',
      duplicateBody: 'প্রশাসকদের পর্যালোচনার জন্য সিস্টেম ওভারল্যাপিং অনুমোদন চিহ্নিত করে।',
      quickActions: 'দ্রুত কাজ',
      verifyStudents: 'শিক্ষার্থী পর্যালোচনা',
      approveProviders: 'প্রদানকারী পর্যালোচনা',
      disbursements: 'বিতরণ',
      impactReport: 'রিপোর্ট',
      recentDisbursements: 'সাম্প্রতিক কার্যক্রম',
      pendingProviders: 'প্রদানকারী তদারকি',
      securityCard: 'অডিট ও নিরাপত্তা',
      securityBody: 'স্বচ্ছতার জন্য গুরুত্বপূর্ণ কাজগুলো লগ করা হয়।',
      generateExport: 'এক্সপোর্ট তৈরি',
      reportPeriod: 'সর্বশেষ সারাংশ',
      attendanceShort: 'উপস্থিতি',
      totalAid: 'মোট প্রাপ্ত সহায়তা',
      needLabel: 'প্রয়োজন স্কোর',
      stepProfile: 'প্রোফাইল ও নথি',
      stepApply: 'আবেদন',
      stepDecision: 'সিদ্ধান্ত',
      submitted: 'জমা দেওয়া',
      noApplicationsYet: 'এখনও কোনো আবেদন নেই।',
      pendingLower: 'পর্যালোচনাধীন',
      approvedLower: 'অনুমোদিত',
      eligibilityBlurb: 'উচ্চ স্কোর মেধা সূচকের তুলনায় বেশি আর্থিক প্রয়োজন নির্দেশ করে।',
      compositeIndex: 'সমন্বিত সূচক (০–১০০)',
      noNotifications: 'কোনো নতুন বিজ্ঞপ্তি নেই।',
      markAllRead: 'সব পঠিত হিসেবে চিহ্নিত করুন',
      cancel: 'বাতিল',
      rejectAppTitle: 'আবেদন প্রত্যাখ্যান',
      rejectAppLead: 'আবেদনকারীকে জানানো হবে। সিদ্ধান্তের কারণ নোট (ঐচ্ছিক) যোগ করতে পারেন।',
      rejectAppStudent: 'আবেদনকারী',
      rejectAppReason: 'কারণ (ঐচ্ছিক)',
      confirmReject: 'প্রত্যাখ্যান নিশ্চিত',
      working: 'কাজ চলছে…',
      withdrawFunds: 'ব্যালান্স উত্তোলন',
      withdrawNoBalance: 'এখনও উত্তোলনযোগ্য ব্যালান্স নেই।',
      withdrawTitle: 'আপনার অ্যাকাউন্টে উত্তোলন',
      withdrawAvailable: 'উপলব্ধ ব্যালান্স:',
      withdrawMethod: 'পেআউট পদ্ধতি',
      withdrawAmount: 'অঙ্ক (বাংলাদেশী টাকা)',
      withdrawWalletNumber: 'মোবাইল ওয়ালেট নম্বর',
      withdrawBankName: 'ব্যাংকের নাম',
      withdrawAccountName: 'অ্যাকাউন্টধারীর নাম',
      withdrawAccountNumber: 'অ্যাকাউন্ট নম্বর',
      withdrawBranch: 'শাখা (ঐচ্ছিক)',
      withdrawRouting: 'রাউটিং নম্বর (ঐচ্ছিক)',
      withdrawNote:
        'আপনি যে তথ্য দেবেন সেখানে টাকা পাঠানো হবে। নম্বর বা ব্যাংক অ্যাকাউন্ট সঠিক কিনা নিশ্চিত করুন।',
      submitWithdrawal: 'উত্তোলন জমা দিন',
      withdrawSuccess: 'উত্তোলনের অনুরোধ জমা হয়েছে।',
      withdrawError: 'উত্তোলন জমা দেওয়া যায়নি।',
      withdrawHistory: 'উত্তোলনের অনুরোধ',
      noWithdrawals: 'এখনও কোনো উত্তোলনের অনুরোধ নেই।',
      disburseModalTitle: 'বিতরণ রেকর্ড করুন',
      disburseModalLead:
        'এই অনুমোদিত আবেদনের জন্য তহবিল নিশ্চিত করুন। এটি প্রোগ্রাম বাজেট আপডেট করে এবং শিক্ষার্থীর ব্যালান্সে জমা ধরে।',
      disburseAmount: 'অঙ্ক (বাংলাদেশী টাকা)',
      disburseMethod: 'পেমেন্ট পদ্ধতি',
      disburseRef: 'লেনদেন রেফারেন্স',
      disburseReleaseDate: 'রিলিজের তারিখ',
      disburseConfirm: 'নিশ্চিত ও রেকর্ড করুন',
      disburseStudent: 'শিক্ষার্থী',
      disburseProgram: 'প্রোগ্রাম',
      disburseDefault: 'পূর্বনির্ধারিত অঙ্ক',
      disburseFundLeft: 'প্রোগ্রামে অবশিষ্ট তহবিল',
      noDisbursements: 'এখনও কোনো বিতরণ রেকর্ড নেই।',
      providerLead:
        'বৃত্তি প্রোগ্রাম কনফিগার করুন এবং যাচাইকৃত শিক্ষার্থীদের কাছে তহবিল কীভাবে যায় তা দেখুন।',
      createProgramTitle: 'প্রোগ্রাম ও তহবিল',
      createProgramSub: 'স্পষ্ট বাজেট ও উপকারভোগী সীমা সহ নতুন সহায়তা চক্র শুরু করুন।',
      createProgramHint:
        'প্রতি শিক্ষার্থীর অঙ্ক, সর্বোচ্চ উপকারভোগী এবং যোগ্যতা নির্ধারণে “নতুন প্রোগ্রাম” ব্যবহার করুন।',
      activePrograms: 'সক্রিয়',
      viewAll: 'সব দেখুন',
      noProgramsYet: 'এখনও কোনো প্রোগ্রাম নেই। আবেদন গ্রহণ শুরু করতে একটি তৈরি করুন।',
      beneficiaryLine: 'উপকারভোগী',
      disbursedShort: 'বিতরিত',
      totalShort: 'মোট',
      transparencyTitle: 'ন্যায়সঙ্গত, ট্রেসযোগ্য বিতরণ',
      atRiskBadge: 'ঝুঁকিতে',
      loading: 'ড্যাশবোর্ড লোড হচ্ছে…',
      exportSoon: 'এক্সপোর্টে বর্তমান ফিল্টার অন্তর্ভুক্ত হবে (শীঘ্রই)।',
      pendingQueue: 'পর্যালোচনায়',
      duplicateHint: 'আবেদন ও বিতরণ মডিউল থেকে ওভারল্যাপিং অনুমোদন পর্যালোচনা করুন।',
      totalStudents: 'শিক্ষার্থী',
      totalProviders: 'প্রদানকারী',
      auditLog: 'অডিট ট্রেইল',
      colAction: 'কাজ',
      colResource: 'রিসোর্স',
      colUser: 'ব্যবহারকারী',
      colTime: 'সময়',
      activeProgramsLabel: 'সক্রিয় প্রোগ্রাম',
      region: {
        dhaka: 'ঢাকা',
        chattogram: 'চট্টগ্রাম',
        rajshahi: 'রাজশাহী',
        khulna: 'খুলনা',
        sylhet: 'সিলেট',
      },
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return localStorage.getItem(STORAGE_KEY) || 'en';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang === 'bn' ? 'bn' : 'en';
  }, [lang]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[lang];
    for (const k of keys) {
      value = value?.[k];
    }
    return value ?? key;
  };

  const toggleLanguage = () => setLang((l) => (l === 'en' ? 'bn' : 'en'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
